FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/malikclaw /usr/local/bin/malikclaw
COPY $TARGETPLATFORM/malikclaw-launcher /usr/local/bin/malikclaw-launcher
COPY $TARGETPLATFORM/malikclaw-launcher-tui /usr/local/bin/malikclaw-launcher-tui

ENTRYPOINT ["malikclaw-launcher"]
CMD ["-public", "-no-browser"]
